### ISSUE TITLE
Error in profile description

### ISSUE THREAD

**Issue by omiroshn** [olehsamoilenko/malloc#4]
I Think you have some errors in the following sentence "_Having a rest writing code after working writing code_".
I can't sleep in bed thinking that you have mistakes.
Please, fix.

**Comment by olehsamoilenko** [comment]
Thanks for opening the ticket, @omiroshn 
Waiting for your proposal for a new status!

**Comment by olehsamoilenko** [comment]
Thanks for your attention
The next item for review is my malloc
